### ISSUE TITLE
Question: Was looking for a way to query recent sales by some form of criteria

### ISSUE THREAD

**Issue by JClutch** [ShaneMaglangit/axie-graphql-documentation#18]
Hey, really enjoying the documentation!

Was wondering if you knew of a way to search for recently sold axies by criteria?

i.e. I'd like to get an idea of what axies are actually selling for that have Christmas Parts or 0 breed aquas. From what I can tell the recently sold search query doesn't appear to take criteria. One work around is to just call for latest sold and filter out based on criteria on my end BUT I don't know what the size limit is or call volume limit is so would like to try and use something more built in if it's available.

Thank you!

**Comment by ShaneMaglangit** [comment]
Hi, I'm happy to hear that!

Unfortunately, the GetRecentlyAxiesSold does not support criteria variables. There is also no other queries that can produce that result that you're looking for.

Thankfully, you can perform the workaround just fine.  Seuchenhund recently clarified that there is no limit to for the GraphQL endpoint (https://discord.com/channels/410537146672349205/505902543927246870/865491830699458590).

**Comment by JClutch** [comment]
Awesome, thank you for the insight!
