### ISSUE TITLE
Ever had to deal with 403 Forbidden response?

### ISSUE THREAD

**Issue by viniciusbo** [ShaneMaglangit/axie-graphql-documentation#25]
Hi,

First of all, thank you for this amazing documentation. It surely is helping a lot of developers like me. I know this is not an issue with your package but there's no information available about this error on the internet, so I've ran out of options.

Back to the point, did you ever had problems with 403 Forbidden responses? I've developed an app to notify people about new axies on the market and while in my local computer the API responses are fine, when I run the very same code on a VPS (DigitalOcean), all API responses are 403 Forbidden.  I've tried to append `?r=myapp` to the end of the GraphQL endpoint, but of course nothing changed. I also tried switching the VPS to get a new IP (maybe that IP was blacklisted for some reason?), but no success.

I think requests are delayed enough (20 secs), so I don't think it's a rate limiting problem or something like that. Any ideas?

Thanks.

**Comment by ShaneMaglangit** [comment]
IPs from Digital Ocean are mostly blacklisted due to prior DDoS attacks presumably coming from DO servers. You can either move to a different provider or use a proxy.
