### ISSUE TITLE
SLP?

### ISSUE THREAD

**Issue by colo13verdadeo** [ShaneMaglangit/axie-graphql-documentation#29]
Can I get how much SLP I have in game?
With what Full GraphQL Query Schema?

**Comment by ShaneMaglangit** [comment]
Unfortunately, the only data accessible from the GraphQL endpoint are mostly marketplace specific data.

For game specific data, you may try and find the game API or use existing proxies from other community developers. You may find these proxies in the main discord channel of Axie Infinity.
