### ISSUE TITLE
POST request also possible or not ?

### ISSUE THREAD

**Issue by Joyen12** [ShaneMaglangit/axie-graphql-documentation#32]
Hi,
Sorry that's not an issue on the code itself but I can't find a way to contact you.

Is there a way to also POST on this API ?

For example claiming SLP or morphing ?

(nothing forbidden by the ToS of course, just simple stuff like that)

**Comment by Capts** [comment]
Also a question.

Im trying to access GetRecentlyAxiesSold and this is the result

```
{
   "errors": [
    {
    "message": "Syntax Error: Expected Name, found String \"operationName\""
   }
   ]
}
```

Any help is appreciated. Thank you

**Comment by ShaneMaglangit** [comment]
@Joyen12 The GraphQL endpoint is strictly for the marketplace data. It cannot perform any Ronin transactions, you would need to interact using the RPC for that.
