### ISSUE TITLE
GetAxieBriefList Operation

### ISSUE THREAD

**Issue by njh18** [ShaneMaglangit/axie-graphql-documentation#33]
I was trying to filter axies using this operation, however, the size is limited to 100 even after i tried to input a size more than 100, is there any way to query a larger size?

**Comment by Capts** [comment]
> 
> 
> I was trying to filter axies using this operation, however, the size is limited to 100 even after i tried to input a size more than 100, is there any way to query a larger size?

HI I just want to ask if do you have any other param when reaching the api endpoint? I'm getting an error that says 
`"Syntax Error: Expected Name, found String \"operationName\""`

Any insight is appreciated. Sorry for asking it on the top of your question. Thanks!

**Comment by ShaneMaglangit** [comment]
@njh18 Unfortunately, there is a fixed limit of 100 and there's no way to get around it. It may even decrease if there's a significant server traffic.

However, you can try looking at GraphQL aliases to tweak your query and have get multiple results at once.

@njh18 Follow the quick start at https://axie-graphql.web.app/getting-started and ensure that you're sending it as JSON.
