### ISSUE TITLE
Get list of all abilities

### ISSUE THREAD

**Issue by mattqs** [ShaneMaglangit/axie-graphql-documentation#34]
Is there a way to get a list of all possible abilities?

With GetAxieDetail you can get the parts abilities for a specific axie, but I would like to get all possible abilities.

**Comment by ShaneMaglangit** [comment]
There are ways to do it but it is not possible with this endpoint.

**Comment by mattqs** [comment]
I could think of one way, by getting axie details from random axies and collecting all unique abilities.

Here is my result:

https://gist.githubusercontent.com/mattqs/aeff0c38d50ca5da7027be34b30acc9e/raw/29112b27d73b9e6bc92f33b096324d6575f90e54/axieAbilities.json
