### ISSUE TITLE
Minimal queries

### ISSUE THREAD

**Issue by phma** [ShaneMaglangit/axie-graphql-documentation#37]
I'm trying to write a C++ program to query the Axie server, and I don't know GraphQL. All the attempted queries I've sent result in "Bad Request". Could you post a minimal query for each operation? For instance, for GetAxieDetail, you could ask for only the back of one specific Axie.

Also is the `\n` in the queries supposed to be sent as `\n` or as a linefeed?

**Comment by ShaneMaglangit** [comment]
The provided examples are in JSON format. You can use it just like any JSON payloads. And yes, that character is for linefeeds.

**Comment by ShaneMaglangit** [comment]
Additionally, there are also example queries on each operation in the pages already. Please do use that as reference.
