### ISSUE TITLE
Get MMR of a player

### ISSUE THREAD

**Issue by stdevCrow** [ShaneMaglangit/axie-graphql-documentation#38]
How to obtain the MMR by using the player's ronin address (or anything else)? Some sites like already fetch leaderboard data, like https://axie.zone/leaderboard

**Comment by ShaneMaglangit** [comment]
The GraphQL API strictly only provides marketplace data. For use cases such as yours, you may use the game API or proxies around it.

**Comment by LateusBetelgeuse** [comment]
I see. Thanks. Just to know. What about axies pricing? The GraphQL API provides information about auctions. But if an axie's price is fixed, I don't see how to obtain such price since action info is null.

**Comment by ShaneMaglangit** [comment]
The axie/axies query provides a field that returns the current listing price of the given Axie. It is still under the auction field.

**Comment by stdevCrow** [comment]
Apparently I tried to get the price of an Axie that I just put to sell, and the market were not aware yet and returned null. So yeah you're right, my bad.
btw I don't understand the non-USD pricing units. I just requested info about this axie: https://marketplace.axieinfinity.com/axie/4741429/
And the auction section returned:
```js
'auction': {
  'startingPrice': '150000000000000000',
  'endingPrice': '150000000000000000',
  'startingTimestamp': '1633902144',
  'endingTimestamp': '1633988544',
  'duration': '86400',
  'timeLeft': '0',
  'currentPrice': '150000000000000000',
  'currentPriceUSD': '561.76',
  'suggestedPrice': '150000000000000000',
  'seller': '0xc1f5233e97f1a859e1aad4dcb32ba2d7426f8fd8',
  'listingIndex': 3189250,
  '__typename': 'Auction'
}
```

**Comment by stdevCrow** [comment]
Nevermind. After checking more Axies it appears that I must divide by 10^18 to get the actual ETH price. Thanks for everything and have a nice day.

**Comment by stdevCrow** [comment]
> The GraphQL API strictly only provides marketplace data. For use cases such as yours, you may use the game API or proxies around it.

A last question: Do you have any idea about where I should start looking such game API or other proxies? I already found one to [check the SLP given a ronin address](https://game-api.skymavis.com/game-api/clients/0xc1f5233e97f1a859e1aad4dcb32ba2d7426f8fd8/items/1). But I have not a single clue about MMR.

**Comment by rpascual0812** [comment]
> > The GraphQL API strictly only provides marketplace data. For use cases such as yours, you may use the game API or proxies around it.
> 
> A last question: Do you have any idea about where I should start looking such game API or other proxies? I already found one to [check the SLP given a ronin address](https://game-api.skymavis.com/game-api/clients/0xc1f5233e97f1a859e1aad4dcb32ba2d7426f8fd8/items/1). But I have not a single clue about MMR.

Have you had any luck getting the MMR?
