### ISSUE TITLE
GetAxieDetail Query

### ISSUE THREAD

**Issue by njh18** [ShaneMaglangit/axie-graphql-documentation#39]
Hello! I would like to check for the getting the price of an axie, i noticed there are two values, one is currentPrice and the other one is currentPriceUSD. I assumed the currentPrice was supposed to be current price of axie in ETH but the numbers are huge, for example if axie is 0.091 then its showing me currentPrice = 91000000000000000.

Basically what i want to ask is what is this currentPrice referring to? and is it possible to get currentPrice in ETH

**Comment by ShaneMaglangit** [comment]
The returned price is in WEI, you would simply need to convert it to the proper denomination to get the ETH equivalent.

```
1 Ether = 1000000000000000000 Wei.
1 Ether = 1000000000000000 Kwei.
1 Ether = 1000000000000 Mwei.
1 Ether = 1000000000 Gwei.
1 Ether = 1000000 Szabo.
1 Ether = 1000 Finney.
1 Ether = 0.001 Kether.
1 Ether = 0.000001 Mether.
```

You may use the following as reference
```go
// WeiToEther converts wei to the proper ETH denomination
func WeiToEther(wei *big.Int) *big.Float {
	f := new(big.Float)
	f.SetPrec(236) //  IEEE 754 octuple-precision binary floating-point format: binary256
	f.SetMode(big.ToNearestEven)
	fWei := new(big.Float)
	fWei.SetPrec(236) //  IEEE 754 octuple-precision binary floating-point format: binary256
	fWei.SetMode(big.ToNearestEven)
	return f.Quo(fWei.SetInt(wei), big.NewFloat(params.Ether))
}
```

Or this dumbed down conversion:
```ts
axie.auction.currentPrice = (parseFloat(axie.auction.currentPrice.slice(0, -14)) / 10000).toString()
```

**Comment by njh18** [comment]
Perfect! Thank you!
