### ISSUE TITLE
GetAxieBriefList does not show auction information 

### ISSUE THREAD

**Issue by shobiiiii** [ShaneMaglangit/axie-graphql-documentation#42]
Hi there

thanks for your providing this document. 
do you know why GetAxieBriefList does show auction information ?
by using GetAxieDetail I could see it is on auction but brief list shows 'None'

**Comment by ShaneMaglangit** [comment]
It should provide the same result. GetAxieBriefList for one, definitely provides auction / listing information. It is the same endpoint used by https://marketplace.axieinfinity.com/axie to retrieved Axies that are on sale. The latter is used when displaying data of a specific axie.
